import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Lightbulb, TrendingUp, AlertCircle, CheckCircle } from 'lucide-react';

interface Recommendation {
  category: string;
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  action_items: string[];
}

interface RecommendationsListProps {
  scanId: number;
}

export default function RecommendationsList({ scanId }: RecommendationsListProps) {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchRecommendations();
  }, [scanId]);

  const fetchRecommendations = async () => {
    try {
      const token = localStorage.getItem('access_token');
      const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api/v1';
      const response = await fetch(
        `${API_BASE_URL}/footprint/recommendations/${scanId}`,
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );

      if (response.ok) {
        const data = await response.json();
        
        // Transform API response to recommendations format
        const recs: Recommendation[] = [];
        
        if (data.profile_recommendations) {
          data.profile_recommendations.forEach((rec: any) => {
            recs.push({
              category: rec.platform,
              priority: rec.priority,
              title: rec.title,
              description: rec.description,
              action_items: rec.action_items
            });
          });
        }
        
        if (data.career_insights) {
          data.career_insights.forEach((insight: any) => {
            recs.push({
              category: 'Career',
              priority: 'medium',
              title: insight.insight_type,
              description: insight.description,
              action_items: insight.recommendations
            });
          });
        }
        
        setRecommendations(recs);
      }
    } catch (error) {
      console.error('Failed to fetch recommendations:', error);
    } finally {
      setLoading(false);
    }
  };

  const getPriorityIcon = (priority: string) => {
    switch (priority) {
      case 'high':
        return <AlertCircle className="w-5 h-5 text-red-600" />;
      case 'medium':
        return <TrendingUp className="w-5 h-5 text-yellow-600" />;
      case 'low':
        return <CheckCircle className="w-5 h-5 text-green-600" />;
      default:
        return <Lightbulb className="w-5 h-5 text-primary-600" />;
    }
  };

  const getPriorityBadge = (priority: string) => {
    const styles = {
      high: 'bg-red-100 text-red-700 border-red-300',
      medium: 'bg-yellow-100 text-yellow-700 border-yellow-300',
      low: 'bg-green-100 text-green-700 border-green-300'
    };
    return styles[priority as keyof typeof styles] || styles.medium;
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-40">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  if (recommendations.length === 0) {
    return (
      <div className="bg-white rounded-2xl p-8 border border-gray-200 shadow-md text-center">
        <Lightbulb className="w-12 h-12 text-gray-400 mx-auto mb-3" />
        <p className="text-gray-600">No recommendations available yet</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl p-6 border border-gray-200 shadow-md">
      <div className="flex items-center gap-3 mb-3">
        <Lightbulb className="w-6 h-6 text-yellow-600" />
        <h3 className="text-xl font-bold text-gray-900">AI-Powered Recommendations</h3>
      </div>
      
      <p className="text-sm text-gray-600 mb-6">
        Personalized recommendations generated by AI after analyzing your GitHub profile, README, projects, and activity patterns.
      </p>

      <div className="space-y-4">
        {recommendations.map((rec, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.1 }}
            className="bg-gradient-to-br from-gray-50 to-white rounded-xl p-5 border border-gray-200 hover:border-primary-500/50 hover:shadow-md transition-all"
          >
            <div className="flex items-start gap-4">
              <div className="flex-shrink-0 mt-1">
                {getPriorityIcon(rec.priority)}
              </div>
              
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <h4 className="text-lg font-semibold text-gray-900">{rec.title}</h4>
                  <span className={`px-2 py-1 rounded-full text-xs font-semibold border ${getPriorityBadge(rec.priority)}`}>
                    {rec.priority.toUpperCase()}
                  </span>
                  <span className="px-2 py-1 rounded-full text-xs font-semibold bg-primary-100 text-primary-700 border border-primary-300">
                    {rec.category}
                  </span>
                </div>
                
                <p className="text-gray-700 mb-3">{rec.description}</p>
                
                {rec.action_items && rec.action_items.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-gray-700">Action Items:</p>
                    <ul className="space-y-1">
                      {rec.action_items.map((item, itemIndex) => (
                        <li key={itemIndex} className="flex items-start gap-2 text-sm text-gray-700">
                          <CheckCircle className="w-4 h-4 text-primary-600 flex-shrink-0 mt-0.5" />
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
